export const IMAGES = {
    logo: "/logo.svg",
    mainBg: "/main-bg.png",
    manager: "/manager.png",
    callIcon: "/call-icon.svg",
    messageIcon: "/message-icon.svg",
    heroBanner: "/Главный баннер.png",
    calBackground: "/Фон для созвона.png",
    case01: "/Кейсы в работе01.png",
    case02: "/Кейсы в работе02.png",
    case03: "/Кейсы в работе03.png",
    project01:
        "/Firefly_Make the apartment a little smaller and place it in a minimalist valuation interface  794770 1.png",
    project02: "/Кейс02.png",
    project03: "/Кейс03.png",
    directionChip: "/direction-01.png",
    directionKeyboard: "/direction-02.png",
    directionPieChart: "/direction-03.png",
    directionTablet: "/direction-04.png",
    directionPaper: "/direction-05.png",
} as const;
