export const IMAGES = {
    logo: "/logo.svg",
    mainBg: "/main-bg.png",
    mainBgMobile: "/main-bg-mobile.png",
    manager: "/manager.png",
    founder: "/founder.png",
    callIcon: "/call-icon.svg",
    messageIcon: "/message-icon.svg",
    calBackground: "/bg-bottom.png",
    case01: "/case-01.png",
    case02: "/case-02.png",
    case03: "/case-03.png",
    caseInWork01: "/case-in-work-01.png",
    caseInWork02: "/case-in-work-02.png",
    caseInWork03: "/case-in-work-03.png",
    directionChip: "/direction-01.png",
    directionKeyboard: "/direction-02.png",
    directionPieChart: "/direction-03.png",
    directionTablet: "/direction-04.png",
    directionPaper: "/direction-05.png",
} as const;
